[package]
name = "red4rs-bindings"
version = "0.1.7"
edition = "2021"

[dependencies]
mint = { version = "0.5", optional = true }
red4rs = { git = "https://github.com/jac3km4/red4rs", rev = "v0.1.7" }

[features]
default = []
mint = ["dep:mint"]
